import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
// Generated by `npm run gen-api` (docusaurus gen-api-docs) from api/hem-api-<version>.yaml.
// The folder docs/reference/api/ is gitignored; every build regenerates it first.
import apiSidebar from './docs/reference/api/sidebar';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

type SidebarItemList = Extract<SidebarsConfig[string], unknown[]>;
type SidebarItem = SidebarItemList[number];

// Doc id of the generated API "info" page (kebab-case of the spec's info.title).
const API_INFO_ID = 'reference/api/encedo-ngine-rest-api';

// The generated slice starts with the info page; it becomes the link of the
// "API Reference" category instead, so drop it from the item list.
const apiItems: SidebarItemList = (Array.isArray(apiSidebar) ? apiSidebar : []).filter(
  (item: SidebarItem) => typeof item === 'string' || !('id' in item) || item.id !== API_INFO_ID,
);

// Explicit sidebar mirroring the original GitBook table of contents (SUMMARY.md).
// Section headers ("Preliminary", "Security", "Reference") are non-collapsible labels,
// as in GitBook: `html` items styled by `.sidebar-heading` in src/css/custom.css.
const sidebars: SidebarsConfig = {
  docs: [
    {type: 'doc', id: 'index', label: 'Welcome'},
    {type: 'html', value: 'Preliminary', className: 'sidebar-heading'},
    'preliminary/quick-start',
    {type: 'html', value: 'Reference', className: 'sidebar-heading'},
    {
      type: 'category',
      label: 'API Reference',
      collapsed: false,
      link: {type: 'doc', id: API_INFO_ID},
      items: apiItems,
    },
  ],
};

export default sidebars;
